// Copyright (c) 2026 Z5Labs and Contributors
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

// This file checks the one thing docs/container/SPEC.md says about the image
// that no listing of it can check: that it trusts no certificate authority, and
// what follows for a run that exports its trace (#198).
//
// # Why the exhaustive listing is not enough on its own
//
// ImageContract already asserts every path in the image, so a CA bundle that
// appeared in one would fail there — the *absence* is checked, on every platform
// published. What no listing checks is the consequence, and the consequence is
// the part a reader is being asked to act on: an OTLP endpoint named with
// `https://` fails certificate verification from inside the image, one named
// with `http://` on the local network does not, and supplying a bundle turns the
// first into the second. Those are three behaviours of a scratch image, and a
// document that stated them without running them would be recording what
// somebody believed about scratch rather than what this image does.
//
// Nothing else here comes near it. The determinism stage configures an OTLP
// endpoint and asserts only that the generated bytes do not move; the image and
// generator-image contracts run the image with no telemetry configured at all. A
// certificate that cannot be verified is a different failure from a connection
// that cannot be made, and it is the one that arrives at the point where a run
// looks like it is working.
//
// # Why the client is a probe and not avroc
//
// The obvious check is `avroc generate` in the image with
// OTEL_EXPORTER_OTLP_ENDPOINT pointed at a TLS collector, and it cannot be
// written: **Dagger sets that variable itself on every exec**, overriding
// whatever the container carried, so that a tool inside reports into Dagger's
// own trace. Measured on v0.21.8 — a container given `ftp://nope`, which
// internal/telemetry rejects outright, starts and warns about nothing, because
// what it read was Dagger's endpoint and not the one the check set. An avroc-run
// version of this check would therefore pass against any image at all, including
// one that trusted nothing and one that trusted everything, which is the worst
// of the available outcomes: a green check nobody has a reason to doubt. (It is
// also why .dagger/main.go's traced run cannot claim that nothing is listening
// at the endpoint it sets.)
//
// So the client is a probe copied into the image the way an adopter copies a
// generator, and it posts an export of its own. What is under test is the root
// store a Go TLS client in this image sees, which is what avroc's exporter,
// every generator's exporter and any third-party plugin's all reach through; the
// exporter itself is internal/telemetry's to test, and it is tested there.
package main

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"dagger/avroc/internal/dagger"
)

const (
	// collectorHost is the name the image resolves the collector by, and it is
	// the name the certificate is issued for. One constant for both, because a
	// mismatch between them fails verification for a reason that has nothing to
	// do with the roots — which is precisely the confusion this check exists to
	// clear up.
	collectorHost = "collector"

	// collectorTLSPort and collectorPlainPort are the two listeners one
	// collector answers on. 4318 is OTLP/HTTP's port and is the plaintext one,
	// because plaintext to a collector on the local network is the shape
	// docs/container/SPEC.md supports; the TLS listener is somewhere else
	// entirely, so that neither probe can reach the other's by accident.
	collectorTLSPort   = 8443
	collectorPlainPort = 4318

	// fixtureDir is where the fixture's executable and its certificate live
	// inside the collector container.
	fixtureDir = "/fixture"

	// fixtureExecutable is that executable, and probeExecutable is where a copy
	// of it lands inside the image under test — the plugin directory, because
	// that is the one directory docs/container/SPEC.md promises a derived image
	// may copy an executable into, and this probe is a derived image's file like
	// any other.
	fixtureExecutable = fixtureDir + "/tls-egress"
	probeExecutable   = pluginDir + "/tls-probe"

	// certPath is the certificate the collector presents, inside the collector
	// container.
	certPath = fixtureDir + "/cert.pem"

	// suppliedRootsPath is the conventional bundle path on a Linux distribution,
	// and where docs/container/SPEC.md's remedy tells a consumer to copy one.
	// It is deliberately not a constant of the image contract: the base image
	// has no such file, and what a consumer's own image puts there is theirs.
	suppliedRootsPath = "/etc/ssl/certs/ca-certificates.crt"
)

// TlsEgress is docs/container/SPEC.md's "No certificate authorities", executed
// (#198). A probe copied into the published image posts an OTLP export to a real
// collector, and each of the three documented outcomes is required to happen:
//
//   - Plaintext to a collector on the local network arrives. That is the
//     supported shape, and it is the one that has to keep working.
//   - TLS to the same collector fails certificate verification, naming x509. An
//     image that trusts no authority cannot verify one, and an operator who
//     configures an `https://` endpoint is entitled to have been told so here
//     rather than at export time.
//   - TLS arrives the moment the consumer supplies the roots, at the
//     conventional bundle path and with no other change. That is what pins the
//     failure above to the absence of roots rather than to some fourth thing
//     missing from a scratch image, and it is what makes the documented remedy
//     an instruction somebody has run.
//
// The first two run against the base image and against the bundle image, which
// is the "generator images inherit whatever the base decides" half: a generator
// image is the base plus one executable, so it inherits an empty trust store,
// and saying so is cheaper than leaving a reader to derive it from a listing.
//
// platform is one of the published platforms; empty is the engine's own. One
// platform, unlike the checks that read the image's filesystem: the decision is
// a property of that filesystem, ImageContract checks it on every platform, and
// what is checked here is the behaviour that follows from it.
//
// +check
// +cache="session"
func (m *Avroc) TlsEgress(
	ctx context.Context,
	// Run the check against the images for this platform, as `GOOS/GOARCH` — one
	// of the published platforms. Empty is the engine's own.
	// +optional
	platform string,
) error {
	p, err := imagePlatform(ctx, platform)
	if err != nil {
		return err
	}

	fixture := m.tlsEgressFixture()
	collector := fixture.
		WithExposedPort(collectorTLSPort).
		WithExposedPort(collectorPlainPort).
		AsService(dagger.ContainerAsServiceOpts{Args: []string{
			fixtureExecutable,
			"-dir", fixtureDir,
			"-tls", fmt.Sprintf(":%d", collectorTLSPort),
			"-plain", fmt.Sprintf(":%d", collectorPlainPort),
		}})
	executable := m.tlsEgressProbe(p)
	roots := fixture.File(certPath)

	images := []struct {
		name  string
		image *dagger.Container
	}{
		{"the base image", m.baseImage(p)},
		{"the bundle image", m.generatorBundleImage(p)},
	}

	var errs []error
	for _, under := range images {
		probe := under.image.WithFile(probeExecutable, executable,
			dagger.ContainerWithFileOpts{Owner: imageUser, Permissions: executableMode})

		errs = append(errs,
			m.checkPlaintextExportArrives(ctx, under.name, probe, collector),
			m.checkTLSExportIsUnverified(ctx, under.name, probe, collector),
			m.checkSuppliedRootsAreEnough(ctx, under.name, probe, collector, roots),
		)
	}
	return errors.Join(errs...)
}

// tlsEgressFixture builds the collector and generates the certificate it will
// present, as one container.
//
// One container for both, because the certificate the check copies into the
// image has to be the certificate the server presents: the service and the File
// both come off this snapshot, so there is no arrangement in which they disagree
// and the failure reads as an untrusted root.
//
// It is built for the engine's own platform and not the image's. The collector
// is the far end of a socket, so what it was compiled for is not a property of
// anything under test — and building it under emulation would cost minutes to
// produce the same bytes on the wire.
func (m *Avroc) tlsEgressFixture() *dagger.Container {
	return dag.Go().
		Container(m.Source).
		WithExec([]string{"go", "build", "-o", fixtureExecutable, "./internal/tools/tls-egress"}).
		WithExec([]string{fixtureExecutable, "-generate", "-dir", fixtureDir, "-host", collectorHost})
}

// tlsEgressProbe builds the executable the check copies into the image, for the
// image's platform.
//
// It goes through the same Build the shipped executables go through, with CGO
// off for the same reason: the image is scratch, and a dynamically linked
// executable copied into it finds no loader and fails with `no such file or
// directory` naming a file that is plainly there. A probe that failed that way
// would look exactly like an image that refused to speak TLS.
func (m *Avroc) tlsEgressProbe(platform dagger.Platform) *dagger.File {
	const pkg = "./internal/tools/tls-egress"

	return dag.Go().Build(m.Source, dagger.GoBuildOpts{
		Pkg:        pkg,
		Platform:   string(platform),
		DisableCgo: true,
	}).File("tls-egress")
}

// checkPlaintextExportArrives requires an export over `http://` to reach the
// collector, which is docs/container/SPEC.md's supported shape.
//
// Nothing else in this repository checks it. The determinism stage points a run
// at an endpoint it makes no claim about, so the one thing no check here can say
// today is whether an export ever leaves the image at all.
func (m *Avroc) checkPlaintextExportArrives(
	ctx context.Context,
	image string,
	probe *dagger.Container,
	collector *dagger.Service,
) error {
	url := fmt.Sprintf("http://%s:%d/v1/traces", collectorHost, collectorPlainPort)

	verdict, err := probeExport(probe, collector, url, nil).Stdout(ctx)
	if err != nil {
		return fmt.Errorf("%s: probing %s: %w", image, url, err)
	}
	if !probeSucceeded(verdict) {
		return fmt.Errorf(
			"%s: an export to %s did not arrive, and plaintext to a collector on the local network is the shape docs/container/SPEC.md supports. The probe said: %s",
			image, url, strings.TrimSpace(verdict))
	}
	return nil
}

// checkTLSExportIsUnverified requires an export over `https://` to fail
// certificate verification.
//
// The failure has to name x509 rather than merely being a failure: a collector
// that was not running, a name that did not resolve and a certificate that could
// not be verified are three different findings, and only the third is the one
// this document promises.
func (m *Avroc) checkTLSExportIsUnverified(
	ctx context.Context,
	image string,
	probe *dagger.Container,
	collector *dagger.Service,
) error {
	url := fmt.Sprintf("https://%s:%d/v1/traces", collectorHost, collectorTLSPort)

	verdict, err := probeExport(probe, collector, url, nil).Stdout(ctx)
	if err != nil {
		return fmt.Errorf("%s: probing %s: %w", image, url, err)
	}
	if probeSucceeded(verdict) {
		return fmt.Errorf(
			"%s: an export to %s was verified against something, and docs/container/SPEC.md says the image carries no CA bundle",
			image, url)
	}
	if !strings.Contains(verdict, unverifiedCertificate) {
		return fmt.Errorf(
			"%s: an export to %s failed without naming %q, so it failed for some reason other than the empty trust store this check is about. The probe said: %s",
			image, url, unverifiedCertificate, strings.TrimSpace(verdict))
	}
	return nil
}

// checkSuppliedRootsAreEnough requires the same export to arrive once the
// consumer supplies the roots.
//
// This is the documented remedy, written the way the document writes it: one
// file at the conventional bundle path and no other change to the image. Without
// it the check above would pass on an image that could not speak TLS at all, or
// had no resolver, or was failing for some fourth reason — and the document
// would be telling an operator to do something nobody had ever run.
func (m *Avroc) checkSuppliedRootsAreEnough(
	ctx context.Context,
	image string,
	probe *dagger.Container,
	collector *dagger.Service,
	roots *dagger.File,
) error {
	url := fmt.Sprintf("https://%s:%d/v1/traces", collectorHost, collectorTLSPort)

	verdict, err := probeExport(probe, collector, url, roots).Stdout(ctx)
	if err != nil {
		return fmt.Errorf("%s: probing %s with a bundle at %s: %w", image, url, suppliedRootsPath, err)
	}
	if !probeSucceeded(verdict) {
		return fmt.Errorf(
			"%s: an export to %s did not arrive with a bundle supplied at %s, which is docs/container/SPEC.md's remedy for TLS egress. The probe said: %s",
			image, url, suppliedRootsPath, strings.TrimSpace(verdict))
	}
	return nil
}

// probeExport runs the probe against url, with the collector bound and — when
// roots is not nil — a bundle at the conventional path.
//
// The three probes differ in exactly two things, the URL and the bundle, so that
// the difference between their verdicts is attributable to those and to nothing
// else.
func probeExport(
	image *dagger.Container,
	collector *dagger.Service,
	url string,
	roots *dagger.File,
) *dagger.Container {
	c := image.WithServiceBinding(collectorHost, collector)

	if roots != nil {
		c = c.WithFile(suppliedRootsPath, roots, dagger.ContainerWithFileOpts{
			Owner:       imageUser,
			Permissions: 0o644,
		})
	}

	return c.WithExec([]string{probeExecutable, "-probe", url})
}

// unverifiedCertificate is what Go's TLS client says when it cannot build a
// chain to a root it holds, and it is a literal here because the pipeline is a
// separate Go module from the one under test. It is the narrowest stable part of
// that message: the sentence around it has been reworded across releases and
// `x509` has not.
const unverifiedCertificate = "x509"

// probeSucceeded reads the fixture's one-line verdict.
func probeSucceeded(verdict string) bool {
	return strings.HasPrefix(strings.TrimSpace(verdict), "ok")
}
