// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Companion
func (r *Binding) AsCompanion() *Companion { // companion (../../../daggerverse/avroc/main.go:104:6)
	q := r.query.Select("asCompanion")

	return &Companion{
		query: q,
	}
}

// Avroc is one composed avroc image, plus the coordinates the next WithGenerator
// call needs to find a published one.
//
// Every function on it is either a builder returning a new Avroc or a terminal
// that runs something, so a call chain reads as the image being assembled and
// then used; nothing here mutates.
type Companion struct { // companion (../../../daggerverse/avroc/main.go:104:6)
	query *querybuilder.Selection

	id *ID
}
type WithCompanionFunc func(r *Companion) *Companion

// With calls the provided function with current Companion.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *Companion) With(f WithCompanionFunc) *Companion {
	return f(r)
}

func (r *Companion) WithGraphQLQuery(q *querybuilder.Selection) *Companion {
	return &Companion{
		query: q,
	}
}

// CompanionGenerateOpts contains options for Companion.Generate
type CompanionGenerateOpts struct {
	//
	// Run as this user, as `UID:GID`. The image's own pinned UID is used when this
	// is empty, which is right for a Dagger caller, since the Directory that comes
	// back is exported by the engine as whoever runs the export. Set it when the
	// output has to arrive owned by a particular UID.
	//
	User string // companion (../../../daggerverse/avroc/main.go:266:2)
}

// Generate runs `avroc generate` over a project and returns the tree it left
// behind.
//
// The whole project comes back, not just the generated files: avroc writes each
// generator's output into the directory the manifest names, which is usually
// inside the source tree, and it maintains avroc.gen.json — the record of what
// the last run produced, which the next run prunes against. So the Directory this
// returns is the project as it should now be committed, and the ordinary use is
// to export it straight over the source:
//
//	dagger call ... generate --source . export --path .
//
// Nothing is passed to avroc but the subcommand. The manifest is the sole source
// of inputs, generators and their options, and a flag here that could override
// any of it would be a second place a project's generation is configured.
func (r *Companion) Generate(source *Directory, opts ...CompanionGenerateOpts) *Directory { // companion (../../../daggerverse/avroc/main.go:256:1)
	assertNotNil("source", source)
	q := r.query.Select("generate")
	for i := len(opts) - 1; i >= 0; i-- {
		// `user` optional argument
		if !querybuilder.IsZeroValue(opts[i].User) {
			q = q.Arg("user", opts[i].User)
		}
	}
	q = q.Arg("source", source)

	return &Directory{
		query: q,
	}
}

// A unique identifier for this Companion.
func (r *Companion) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Companion) XXX_GraphQLType() string {
	return "Companion"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Companion) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Companion) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Companion) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Companion) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Companion{query: selectNode(dag.query, id, "Companion")}
	return nil
}

// Image is the composed image, for a caller who wants to do something with it
// other than generate: publish it to their own registry, run a different avroc
// subcommand, or look at what ended up in it.
//
// Publishing one is a reasonable thing to do — it is the same image a Dockerfile
// would have produced — but it is not a release of avroc and carries none of the
// signatures or attestations one does.
func (r *Companion) Image() *Container { // companion (../../../daggerverse/avroc/main.go:237:1)
	q := r.query.Select("image")

	return &Container{
		query: q,
	}
}

// CompanionWithGeneratorOpts contains options for Companion.WithGenerator
type CompanionWithGeneratorOpts struct {
	//
	// Take the executable from this image instead of pulling the published
	// generator image for name. Any image carrying the generator in the plugin
	// directory will do, including one that is not published.
	//
	Image *Container // companion (../../../daggerverse/avroc/main.go:184:2)
}

// WithGenerator adds one generator to the image by copying its executable out of
// a generator image.
//
// This is the whole of "adding a plugin without writing a Dockerfile": the file
// is taken from the published image at the path docs/container/SPEC.md promises,
// which is what `COPY --from` does, and works just as well for a generator image
// this project has never heard of — pass it as image.
//
// Repeated calls compose, so a project whose manifest names three generators is
// three calls and one image.
func (r *Companion) WithGenerator(name string, opts ...CompanionWithGeneratorOpts) *Companion { // companion (../../../daggerverse/avroc/main.go:175:1)
	q := r.query.Select("withGenerator")
	for i := len(opts) - 1; i >= 0; i-- {
		// `image` optional argument
		if !querybuilder.IsZeroValue(opts[i].Image) {
			q = q.Arg("image", opts[i].Image)
		}
	}
	q = q.Arg("name", name)

	return &Companion{
		query: q,
	}
}

// WithGeneratorExecutable adds one generator to the image from an executable
// file, for a generator that ships no image — most often one the caller has just
// built in the same pipeline.
//
// The file has to be a Linux executable for the image's platform, statically
// linked or matched to whatever the image provides, which for avroc's own scratch
// base means static. That is the same requirement docs/container/SPEC.md's worked
// example states as `CGO_ENABLED=0`, and it is the caller's to meet: nothing here
// can check it, and a dynamically linked generator fails at exec time with the
// kernel's message rather than avroc's.
func (r *Companion) WithGeneratorExecutable(name string, executable *File) *Companion { // companion (../../../daggerverse/avroc/main.go:205:1)
	assertNotNil("executable", executable)
	q := r.query.Select("withGeneratorExecutable")
	q = q.Arg("name", name)
	q = q.Arg("executable", executable)

	return &Companion{
		query: q,
	}
}

// AsNode returns this Companion as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Companion) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Create or update a binding of type Companion in the environment
func (r *Env) WithCompanionInput(name string, value *Companion, description string) *Env { // companion (../../../daggerverse/avroc/main.go:104:6)
	assertNotNil("value", value)
	q := r.query.Select("withCompanionInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Companion output to be assigned in the environment
func (r *Env) WithCompanionOutput(name string, description string) *Env { // companion (../../../daggerverse/avroc/main.go:104:6)
	q := r.query.Select("withCompanionOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// CompanionOpts contains options for Query.Companion
type CompanionOpts struct {
	//
	// The avroc release to run, as a `<tag>` on the published images. A
	// major-version tag like v0 follows releases and a full version like v0.2.0
	// pins one; a build that must not move at all pins a digest, which is what
	// --image is for.
	//
	//
	// Default: "v0"
	Version string // companion (../../../daggerverse/avroc/main.go:136:2)
	//
	// The registry repository the images are pulled from, as `<host>/<path>` with
	// no tag. The generator images derive from it by the rule this project
	// publishes them under: <repository>-gen-<name>.
	//
	// It is an argument because where the images live is not something
	// docs/container/SPEC.md promises — a mirror, an internal registry or an
	// air-gapped copy serving the same digests satisfies every requirement in that
	// document identically, and a caller behind one should not have to give up
	// this module to use it.
	//
	//
	// Default: "ghcr.io/z5labs/avroc"
	Repository string // companion (../../../daggerverse/avroc/main.go:148:2)
	//
	// Run in this image instead of pulling one. It has to keep the promises
	// docs/container/SPEC.md makes — avroc as the entrypoint, the plugin directory
	// on PATH — because that is all this module drives it through.
	//
	// This is how avroc's own pipeline checks the module against the images it
	// just built rather than against the last release, and how a caller tries a
	// change to avroc before it ships.
	//
	Image *Container // companion (../../../daggerverse/avroc/main.go:157:2)
}

// New selects the avroc release to run.
//
// The defaults pull the published base image, which carries the CLI and no
// generator at all — the generators are separate images (docs/container/SPEC.md,
// "avroc's own generators"), so a project that generates anything needs at least
// one WithGenerator call. That is one call more than a bundle image would cost
// and it is deliberate: which generators are in the image is the caller's
// manifest, and an image that shipped all of them would decide it for them.
func (r *Query) Companion(opts ...CompanionOpts) *Companion { // companion (../../../daggerverse/avroc/main.go:129:1)
	q := r.query.Select("companion")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `repository` optional argument
		if !querybuilder.IsZeroValue(opts[i].Repository) {
			q = q.Arg("repository", opts[i].Repository)
		}
		// `image` optional argument
		if !querybuilder.IsZeroValue(opts[i].Image) {
			q = q.Arg("image", opts[i].Image)
		}
	}

	return &Companion{
		query: q,
	}
}
