// Copyright (c) 2026 Z5Labs and Contributors
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

package avrocgengo

import (
	"fmt"
	"strings"

	"github.com/z5labs/avroc/avrocpb"
)

const fileHeaderNoImports = `// Code generated by avroc-gen-go. DO NOT EDIT.

package %s
`

const fileHeaderWithAvrolib = `// Code generated by avroc-gen-go. DO NOT EDIT.

package %s

import (
	avro "github.com/z5labs/avro-go"
)
`

const fileHeaderWithAvrolibAndFmt = `// Code generated by avroc-gen-go. DO NOT EDIT.

package %s

import (
	"fmt"

	avro "github.com/z5labs/avro-go"
)
`

// codeBuilder helps construct Go source code.
type codeBuilder struct {
	buf strings.Builder
}

func (cb *codeBuilder) String() string {
	return cb.buf.String()
}

func (cb *codeBuilder) writef(format string, args ...any) {
	fmt.Fprintf(&cb.buf, format, args...)
}

func (cb *codeBuilder) writeln(s string) {
	cb.buf.WriteString(s)
	cb.buf.WriteByte('\n')
}

func (cb *codeBuilder) newline() {
	cb.buf.WriteByte('\n')
}

// generateFileCode generates the complete Go source code for a schema.
func generateFileCode(packageName string, schema *avrocpb.Schema, singleObject bool, fp [8]byte) string {
	cb := &codeBuilder{}

	// Collect all types to generate (including unions)
	types := collectTypes(schema)

	// Check if we need avro import (for types with MarshalAvroBinary)
	needsAvrolib := needsAvrolibImport(types)
	needsFmt := needsFmtImport(types)

	if needsAvrolib && needsFmt {
		cb.writef(fileHeaderWithAvrolibAndFmt, packageName)
	} else if needsAvrolib {
		cb.writef(fileHeaderWithAvrolib, packageName)
	} else {
		cb.writef(fileHeaderNoImports, packageName)
	}

	// Determine the primary record name so we only emit Fingerprint for it.
	primaryRecordName := schemaRecordName(schema)

	for _, t := range types {
		cb.newline()
		generateType(cb, t)
		generateMarshalMethod(cb, t)
		generateUnmarshalMethod(cb, t)

		if singleObject {
			if rec, ok := t.typ.Type.(*avrocpb.Type_Record); ok {
				if rec.Record.GetName() == primaryRecordName {
					name := toPascalCase(rec.Record.GetName())
					generateFingerprintMethod(cb, name, fp)
				}
			}
		}
	}

	return cb.String()
}

// schemaRecordName returns the name of the schema's primary record type, or the
// empty string when it has none.
//
// The primary type is the definition itself: avroc writes a named type out in
// full at its first use, and the schema's own type is the first use of whatever
// it names. There is no reference here to chase back to a declaration.
func schemaRecordName(schema *avrocpb.Schema) string {
	if rec, ok := schema.GetType().GetType().(*avrocpb.Type_Record); ok {
		return rec.Record.GetName()
	}
	return ""
}

// needsAvrolibImport checks if any types need the avrolib import.
// Returns true if there are any records, enums, fixed, or union types.
func needsAvrolibImport(types []typeToGenerate) bool {
	for _, ttg := range types {
		switch ttg.typ.Type.(type) {
		case *avrocpb.Type_Record, *avrocpb.Type_EnumType, *avrocpb.Type_Fixed, *avrocpb.Type_Union:
			return true
		}
	}
	return false
}

// needsFmtImport checks if any types need the fmt import.
// Returns true if there are union types (for unmarshal error messages).
func needsFmtImport(types []typeToGenerate) bool {
	for _, ttg := range types {
		if _, ok := ttg.typ.Type.(*avrocpb.Type_Union); ok {
			return true
		}
	}
	return false
}

// typeToGenerate wraps a type with optional context (e.g., field name for unions).
type typeToGenerate struct {
	typ        *avrocpb.Type
	recordName string // For unions: the containing record name
	fieldName  string // For unions: the field name this union belongs to
}

// collectTypes extracts all types that need to be generated from a schema.
func collectTypes(schema *avrocpb.Schema) []typeToGenerate {
	var types []typeToGenerate

	// Add the main schema type if present
	if schema.Type != nil {
		types = append(types, collectTypeAndNested(schema.Type, "", "")...)
	}

	// Add additional types
	for _, t := range schema.Types {
		types = append(types, collectTypeAndNested(t, "", "")...)
	}

	return types
}

// collectTypeAndNested collects a type and any nested types that need generation.
func collectTypeAndNested(t *avrocpb.Type, recordName string, parentFieldName string) []typeToGenerate {
	var types []typeToGenerate

	switch v := t.Type.(type) {
	case *avrocpb.Type_Record:
		// First collect nested types from fields
		recName := v.Record.GetName()
		for _, f := range v.Record.Fields {
			nested := collectNestedTypes(f.Type, recName, f.GetName())
			types = append(types, nested...)
		}
		// Then add the record itself
		types = append(types, typeToGenerate{typ: t})

	case *avrocpb.Type_EnumType:
		types = append(types, typeToGenerate{typ: t})

	case *avrocpb.Type_Fixed:
		types = append(types, typeToGenerate{typ: t})

	case *avrocpb.Type_Union:
		types = append(types, typeToGenerate{typ: t, recordName: recordName, fieldName: parentFieldName})

	case *avrocpb.Type_Array:
		// Check if items contain nested types
		nested := collectNestedTypes(v.Array.Items, recordName, "")
		types = append(types, nested...)
	}

	return types
}

// collectNestedTypes finds types nested within a type that need generation.
func collectNestedTypes(t *avrocpb.Type, recordName string, fieldName string) []typeToGenerate {
	if t == nil {
		return nil
	}

	switch v := t.Type.(type) {
	case *avrocpb.Type_Union:
		return []typeToGenerate{{typ: t, recordName: recordName, fieldName: fieldName}}

	case *avrocpb.Type_Array:
		return collectNestedTypes(v.Array.Items, recordName, fieldName)

	case *avrocpb.Type_Record:
		return collectTypeAndNested(t, recordName, fieldName)

	case *avrocpb.Type_EnumType:
		return collectTypeAndNested(t, recordName, fieldName)

	case *avrocpb.Type_Fixed:
		return collectTypeAndNested(t, recordName, fieldName)
	}

	return nil
}

// generateType generates the Go code for a single type.
func generateType(cb *codeBuilder, ttg typeToGenerate) {
	t := ttg.typ

	switch v := t.Type.(type) {
	case *avrocpb.Type_Record:
		generateRecord(cb, v.Record)
	case *avrocpb.Type_EnumType:
		generateEnum(cb, v.EnumType)
	case *avrocpb.Type_Fixed:
		generateFixed(cb, v.Fixed)
	case *avrocpb.Type_Union:
		generateUnion(cb, v.Union, ttg.recordName, ttg.fieldName)
	}
}

// generateRecord generates a Go struct for an Avro record.
func generateRecord(cb *codeBuilder, r *avrocpb.Record) {
	name := toPascalCase(r.GetName())
	recordName := r.GetName()

	cb.writef("// %s is a generated Avro record type.\n", name)
	cb.writef("type %s struct {\n", name)

	for _, f := range r.Fields {
		fieldName := toFieldName(f.GetName())
		fieldType := fieldTypeString(f, recordName)
		cb.writef("\t%s %s\n", fieldName, fieldType)
	}

	cb.writeln("}")
}

// generateEnum generates a Go type and constants for an Avro enum.
func generateEnum(cb *codeBuilder, e *avrocpb.Enum) {
	name := toPascalCase(e.GetName())

	cb.writef("// %s is a generated Avro enum type.\n", name)
	cb.writef("type %s int\n\n", name)

	cb.writeln("const (")
	for i, v := range e.Values {
		valueName := toPascalCase(v.GetValue())
		cb.writef("\t%s%s %s = %d\n", name, valueName, name, i)
	}
	cb.writeln(")")
}

// generateFixed generates a Go type for an Avro fixed type.
func generateFixed(cb *codeBuilder, f *avrocpb.Fixed) {
	name := toPascalCase(f.GetName())

	cb.writef("// %s is a generated Avro fixed type.\n", name)
	cb.writef("type %s [%d]byte\n", name, f.GetSize())
}

// generateUnion generates a Go interface and concrete types for an Avro union.
func generateUnion(cb *codeBuilder, u *avrocpb.Union, recordName string, fieldName string) {
	unionName := unionTypeName(recordName, fieldName)
	methodName := "is" + unionName

	cb.writef("// %s is a generated Avro union type.\n", unionName)
	cb.writef("type %s interface {\n", unionName)
	cb.writef("\t%s()\n", methodName)
	cb.writef("\tMarshalAvroBinary(w *avro.BinaryWriter) error\n")
	cb.writeln("}")

	for _, t := range u.Types {
		cb.newline()
		generateUnionMember(cb, unionName, t)
	}
}

// generateUnionMember generates a concrete type for a union member.
func generateUnionMember(cb *codeBuilder, unionName string, t *avrocpb.Type) {
	memberName := unionMemberName(unionName, t)
	methodName := "is" + unionName

	if isNullType(t) {
		cb.writef("// %s represents the null value in the union.\n", memberName)
		cb.writef("type %s struct{}\n\n", memberName)
		cb.writef("func (_ %s) %s() {}\n", memberName, methodName)
	} else {
		goType := goTypeForType(t, "")
		cb.writef("// %s wraps %s in the union.\n", memberName, goType)
		cb.writef("type %s struct {\n", memberName)
		cb.writef("\tValue %s\n", goType)
		cb.writeln("}")
		cb.newline()
		cb.writef("func (_ %s) %s() {}\n", memberName, methodName)
	}
}

// fieldTypeString returns the Go type string for a field.
func fieldTypeString(f *avrocpb.Field, recordName string) string {
	if f == nil || f.Type == nil {
		return "any"
	}

	// Check if this is a union type - use the record and field name to generate union type name
	if f.Type.GetUnion() != nil {
		return unionTypeName(recordName, f.GetName())
	}

	return goTypeForType(f.Type, "")
}
