// Copyright (c) 2026 Z5Labs and Contributors
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: generate_response.proto

package avrocpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The response message for the Generate RPC method.
type GenerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of generated output files.
	OutputFiles   []string `protobuf:"bytes,1,rep,name=output_files,json=outputFiles" json:"output_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_generate_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_generate_response_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateResponse) GetOutputFiles() []string {
	if x != nil {
		return x.OutputFiles
	}
	return nil
}

var File_generate_response_proto protoreflect.FileDescriptor

const file_generate_response_proto_rawDesc = "" +
	"\n" +
	"\x17generate_response.proto\"5\n" +
	"\x10GenerateResponse\x12!\n" +
	"\foutput_files\x18\x01 \x03(\tR\voutputFilesB2Z0github.com/z5labs/avroc/internal/avrocpb;avrocpbb\beditionsp\xe8\a"

var (
	file_generate_response_proto_rawDescOnce sync.Once
	file_generate_response_proto_rawDescData []byte
)

func file_generate_response_proto_rawDescGZIP() []byte {
	file_generate_response_proto_rawDescOnce.Do(func() {
		file_generate_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generate_response_proto_rawDesc), len(file_generate_response_proto_rawDesc)))
	})
	return file_generate_response_proto_rawDescData
}

var file_generate_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_generate_response_proto_goTypes = []any{
	(*GenerateResponse)(nil), // 0: GenerateResponse
}
var file_generate_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_generate_response_proto_init() }
func file_generate_response_proto_init() {
	if File_generate_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generate_response_proto_rawDesc), len(file_generate_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_generate_response_proto_goTypes,
		DependencyIndexes: file_generate_response_proto_depIdxs,
		MessageInfos:      file_generate_response_proto_msgTypes,
	}.Build()
	File_generate_response_proto = out.File
	file_generate_response_proto_goTypes = nil
	file_generate_response_proto_depIdxs = nil
}
