// Copyright (c) 2026 Z5Labs and Contributors
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: generate_response.proto

package avrocpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One streamed chunk of generated output. A file is the ordered concatenation
// of all chunks sharing the same `path`, terminated by the chunk whose `last`
// is true.
type GenerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path of the generated file, relative to the output root, using forward
	// slashes regardless of OS. avroc joins this onto the -<name>_out directory
	// and MUST reject absolute paths or any path that escapes the output root
	// (e.g. containing "..").
	Path *string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	// A chunk of the file's content. Each message is kept comfortably under the
	// 4MB default MaxRecvMsgSize so the limit never needs raising.
	Content []byte `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	// True on the final chunk for `path`.
	Last          *bool `protobuf:"varint,3,opt,name=last" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_generate_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_generate_response_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateResponse) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *GenerateResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GenerateResponse) GetLast() bool {
	if x != nil && x.Last != nil {
		return *x.Last
	}
	return false
}

var File_generate_response_proto protoreflect.FileDescriptor

const file_generate_response_proto_rawDesc = "" +
	"\n" +
	"\x17generate_response.proto\"T\n" +
	"\x10GenerateResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04lastB2Z0github.com/z5labs/avroc/internal/avrocpb;avrocpbb\beditionsp\xe8\a"

var (
	file_generate_response_proto_rawDescOnce sync.Once
	file_generate_response_proto_rawDescData []byte
)

func file_generate_response_proto_rawDescGZIP() []byte {
	file_generate_response_proto_rawDescOnce.Do(func() {
		file_generate_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generate_response_proto_rawDesc), len(file_generate_response_proto_rawDesc)))
	})
	return file_generate_response_proto_rawDescData
}

var file_generate_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_generate_response_proto_goTypes = []any{
	(*GenerateResponse)(nil), // 0: GenerateResponse
}
var file_generate_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_generate_response_proto_init() }
func file_generate_response_proto_init() {
	if File_generate_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generate_response_proto_rawDesc), len(file_generate_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_generate_response_proto_goTypes,
		DependencyIndexes: file_generate_response_proto_depIdxs,
		MessageInfos:      file_generate_response_proto_msgTypes,
	}.Build()
	File_generate_response_proto = out.File
	file_generate_response_proto_goTypes = nil
	file_generate_response_proto_depIdxs = nil
}
