// Copyright (c) 2026 Z5Labs and Contributors
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: generator.proto

package avrocpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_generator_proto protoreflect.FileDescriptor

const file_generator_proto_rawDesc = "" +
	"\n" +
	"\x0fgenerator.proto\x1a\x16generate_request.proto\x1a\x17generate_response.proto2<\n" +
	"\tGenerator\x12/\n" +
	"\bGenerate\x12\x10.GenerateRequest\x1a\x11.GenerateResponseB2Z0github.com/z5labs/avroc/internal/avrocpb;avrocpbb\beditionsp\xe8\a"

var file_generator_proto_goTypes = []any{
	(*GenerateRequest)(nil),  // 0: GenerateRequest
	(*GenerateResponse)(nil), // 1: GenerateResponse
}
var file_generator_proto_depIdxs = []int32{
	0, // 0: Generator.Generate:input_type -> GenerateRequest
	1, // 1: Generator.Generate:output_type -> GenerateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_generator_proto_init() }
func file_generator_proto_init() {
	if File_generator_proto != nil {
		return
	}
	file_generate_request_proto_init()
	file_generate_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generator_proto_rawDesc), len(file_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generator_proto_goTypes,
		DependencyIndexes: file_generator_proto_depIdxs,
	}.Build()
	File_generator_proto = out.File
	file_generator_proto_goTypes = nil
	file_generator_proto_depIdxs = nil
}
