// Copyright (c) 2026 Z5Labs and Contributors
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: sort_order.proto

package avrocpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SortOrder represents the sort order of a field in a record.
type SortOrder int32

const (
	SortOrder_SORT_ORDER_ASC    SortOrder = 0
	SortOrder_SORT_ORDER_DESC   SortOrder = 1
	SortOrder_SORT_ORDER_IGNORE SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_ASC",
		1: "SORT_ORDER_DESC",
		2: "SORT_ORDER_IGNORE",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_ASC":    0,
		"SORT_ORDER_DESC":   1,
		"SORT_ORDER_IGNORE": 2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_sort_order_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_sort_order_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_sort_order_proto_rawDescGZIP(), []int{0}
}

var File_sort_order_proto protoreflect.FileDescriptor

const file_sort_order_proto_rawDesc = "" +
	"\n" +
	"\x10sort_order.proto*K\n" +
	"\tSortOrder\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x00\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x01\x12\x15\n" +
	"\x11SORT_ORDER_IGNORE\x10\x02B2Z0github.com/z5labs/avroc/internal/avrocpb;avrocpbb\beditionsp\xe8\a"

var (
	file_sort_order_proto_rawDescOnce sync.Once
	file_sort_order_proto_rawDescData []byte
)

func file_sort_order_proto_rawDescGZIP() []byte {
	file_sort_order_proto_rawDescOnce.Do(func() {
		file_sort_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sort_order_proto_rawDesc), len(file_sort_order_proto_rawDesc)))
	})
	return file_sort_order_proto_rawDescData
}

var file_sort_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sort_order_proto_goTypes = []any{
	(SortOrder)(0), // 0: SortOrder
}
var file_sort_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sort_order_proto_init() }
func file_sort_order_proto_init() {
	if File_sort_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sort_order_proto_rawDesc), len(file_sort_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sort_order_proto_goTypes,
		DependencyIndexes: file_sort_order_proto_depIdxs,
		EnumInfos:         file_sort_order_proto_enumTypes,
	}.Build()
	File_sort_order_proto = out.File
	file_sort_order_proto_goTypes = nil
	file_sort_order_proto_depIdxs = nil
}
