// Code generated by avroc-gen-go. DO NOT EDIT.

package stream

import (
	"io"
	"iter"

	avro "github.com/z5labs/avro-go"
)

// Event is a generated Avro record type.
type Event struct {
	Id    int64
	Value float64
	Ok    bool
}

func (x *Event) MarshalAvroBinary(w *avro.BinaryWriter) error {
	var err error
	err = w.WriteLong(x.Id)
	if err != nil {
		return err
	}
	err = w.WriteDouble(x.Value)
	if err != nil {
		return err
	}
	err = w.WriteBool(x.Ok)
	if err != nil {
		return err
	}
	return nil
}

func (x *Event) UnmarshalAvroBinary(r *avro.BinaryReader) error {
	var err error
	x.Id, err = r.ReadLong()
	if err != nil {
		return err
	}
	x.Value, err = r.ReadDouble()
	if err != nil {
		return err
	}
	x.Ok, err = r.ReadBool()
	if err != nil {
		return err
	}
	return nil
}

// EventReader reads a stream of Event values from an Avro array without
// materialising it.
//
// The embedded [avro.ArrayReader] is the whole of the block framing. Its Next
// decodes into a destination the caller owns, so one Event can be reused for the
// whole stream, and its SkipBlock discards a sized block without decoding any
// item at all.
type EventReader struct {
	*avro.ArrayReader
}

// NewEventReader returns a reader decoding the Avro array in r.
func NewEventReader(r io.Reader) *EventReader {
	return &EventReader{ArrayReader: avro.NewArrayReader(avro.NewBinaryReader(r))}
}

// All returns an iterator over the stream's remaining items, decoding each
// into a newly allocated Event.
//
// Iteration stops at the array's terminating block, and at the first error,
// which is yielded once as a nil *Event alongside it. Call the embedded reader's
// Next directly to decode into a destination of your own instead.
func (x *EventReader) All() iter.Seq2[*Event, error] {
	return func(yield func(*Event, error) bool) {
		for {
			v := new(Event)
			ok, err := x.ArrayReader.Next(v)
			if err != nil {
				yield(nil, err)
				return
			}
			if !ok {
				return
			}
			if !yield(v, nil) {
				return
			}
		}
	}
}

// StreamEvents returns an iterator over the Event values encoded as an Avro array
// in r. It is the ordinary way to consume such a stream:
//
//	for v, err := range StreamEvents(r) {
//		...
//	}
func StreamEvents(r io.Reader) iter.Seq2[*Event, error] {
	return NewEventReader(r).All()
}

// EventWriter writes a stream of Event values as an Avro array without
// materialising it.
//
// The embedded [avro.ArrayWriter] is the whole of the block framing, including
// the zero-count block that terminates the array. Its Close writes that block,
// so Close is neither optional nor merely a flush: a writer that is never
// closed leaves a truncated array behind, which reading it back reports as
// [avro.ErrTruncatedArray]. WriteEvents closes for you.
type EventWriter struct {
	*avro.ArrayWriter
}

// NewEventWriter returns a writer encoding an Avro array of Event to w.
//
// By default the blocks it emits declare no size and nothing is buffered: each
// item reaches w as it is written. Pass [avro.WithSizedBlocks] to batch items
// into blocks that declare their encoded size, which a reader can discard with
// SkipBlock instead of decoding, at the cost of a bounded buffer.
func NewEventWriter(w io.Writer, opts ...avro.ArrayWriterOption) *EventWriter {
	return &EventWriter{ArrayWriter: avro.NewArrayWriter(avro.NewBinaryWriter(w), opts...)}
}

// Write encodes v as the next item of the array.
//
// It is the embedded writer's Write with the stream's item type filled in: a
// stream of Event holds Event values, and this is what makes writing anything
// else a compile error rather than a convention. Call the embedded writer's
// Write directly to write any [avro.BinaryMarshaler] instead.
func (x *EventWriter) Write(v *Event) error {
	return x.ArrayWriter.Write(v)
}

// WriteEvents encodes the Event values f writes as an Avro array in w,
// terminating the array once f returns without error. It is the ordinary way
// to produce such a stream:
//
//	err := WriteEvents(w, func(s *EventWriter) error {
//		for _, v := range events {
//			if err := s.Write(v); err != nil {
//				return err
//			}
//		}
//		return nil
//	})
//
// If f returns an error the array is left unterminated, since a partial array
// should not be presented as a complete one.
func WriteEvents(w io.Writer, f func(*EventWriter) error, opts ...avro.ArrayWriterOption) error {
	return avro.WriteArray(avro.NewBinaryWriter(w), func(a *avro.ArrayWriter) error {
		return f(&EventWriter{ArrayWriter: a})
	}, opts...)
}
