// Copyright (c) 2026 Z5Labs and Contributors
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

edition = "2023";

option go_package = "github.com/z5labs/avroc/internal/avrocpb;avrocpb";

import "schema.proto";
import "option.proto";

// The request message for the Generate RPC method.
message GenerateRequest {
    // The directory where the generated code should be placed.
    string output_directory = 1;

    // Options to customize the code generation process.
    repeated Option options = 2;

    // The Avro schemas to be generate code for.
    repeated Schema schemas = 3;
}