// Copyright (c) 2026 Z5Labs and Contributors
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

edition = "2023";

option go_package = "github.com/z5labs/avroc/internal/avrocpb;avrocpb";

import "generate_request.proto";
import "generate_response.proto";

// The Generator service defines the RPC method for generating code from Avro schemas.
service Generator {
    // The Generate method takes a GenerateRequest and returns a GenerateResponse.
    rpc Generate (GenerateRequest) returns (GenerateResponse);
}