// Copyright (c) 2026 Z5Labs and Contributors
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: generate_request.proto

package avrocpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for the Generate RPC method. It is the descriptor
// docs/ir/SPEC.md specifies: the version identifying the contract it was
// written against, the options for the invocation it belongs to, and the
// resolved schemas.
type GenerateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IR contract version this descriptor was written against: a single
	// monotonic integer, never a major and a minor. The only question a
	// consumer can act on is whether it understands the descriptor in front of
	// it, and a minor number exists to let it answer "not entirely, but I will
	// continue anyway".
	//
	// A producer MUST set it on every descriptor it emits. A consumer MUST read
	// it before processing anything else, and MUST refuse a version it does not
	// know — failing the invocation with a diagnostic naming the version it
	// found and the version it understands — rather than proceeding on the
	// parts it recognises.
	//
	// Zero is never emitted by a conforming producer. Field number 3 rather
	// than 1 only because 1 and 2 were already assigned; the number carries no
	// meaning and says nothing about the order a consumer reads fields in.
	Version *int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	// Options to customize the code generation process.
	Options []*Option `protobuf:"bytes,1,rep,name=options" json:"options,omitempty"`
	// The Avro schemas to be generate code for.
	Schemas       []*Schema `protobuf:"bytes,2,rep,name=schemas" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_generate_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_generate_request_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *GenerateRequest) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *GenerateRequest) GetSchemas() []*Schema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

var File_generate_request_proto protoreflect.FileDescriptor

const file_generate_request_proto_rawDesc = "" +
	"\n" +
	"\x16generate_request.proto\x1a\fschema.proto\x1a\foption.proto\"q\n" +
	"\x0fGenerateRequest\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12!\n" +
	"\aoptions\x18\x01 \x03(\v2\a.OptionR\aoptions\x12!\n" +
	"\aschemas\x18\x02 \x03(\v2\a.SchemaR\aschemasB)Z'github.com/z5labs/avroc/avrocpb;avrocpbb\beditionsp\xe8\a"

var (
	file_generate_request_proto_rawDescOnce sync.Once
	file_generate_request_proto_rawDescData []byte
)

func file_generate_request_proto_rawDescGZIP() []byte {
	file_generate_request_proto_rawDescOnce.Do(func() {
		file_generate_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generate_request_proto_rawDesc), len(file_generate_request_proto_rawDesc)))
	})
	return file_generate_request_proto_rawDescData
}

var file_generate_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_generate_request_proto_goTypes = []any{
	(*GenerateRequest)(nil), // 0: GenerateRequest
	(*Option)(nil),          // 1: Option
	(*Schema)(nil),          // 2: Schema
}
var file_generate_request_proto_depIdxs = []int32{
	1, // 0: GenerateRequest.options:type_name -> Option
	2, // 1: GenerateRequest.schemas:type_name -> Schema
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_generate_request_proto_init() }
func file_generate_request_proto_init() {
	if File_generate_request_proto != nil {
		return
	}
	file_schema_proto_init()
	file_option_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generate_request_proto_rawDesc), len(file_generate_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_generate_request_proto_goTypes,
		DependencyIndexes: file_generate_request_proto_depIdxs,
		MessageInfos:      file_generate_request_proto_msgTypes,
	}.Build()
	File_generate_request_proto = out.File
	file_generate_request_proto_goTypes = nil
	file_generate_request_proto_depIdxs = nil
}
