// Copyright (c) 2026 Z5Labs and Contributors
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: type_ref_kind.proto

package avrocpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TypeRefKind states whether a Reference names an Avro primitive or a named
// type the same descriptor defines. It is a closed set: a consumer MUST switch
// over it and MUST fail on a member it does not recognise rather than guessing.
//
// It exists so that no consumer recovers the classification by matching a name
// against Avro's list of primitives.
type TypeRefKind int32

const (
	// Never emitted by a conforming producer. A consumer MUST reject it.
	TypeRefKind_TYPE_REF_KIND_UNSPECIFIED TypeRefKind = 0
	// The reference names one of Avro's primitive types.
	TypeRefKind_TYPE_REF_KIND_PRIMITIVE TypeRefKind = 1
	// The reference names a record, enum or fixed the same descriptor defines.
	TypeRefKind_TYPE_REF_KIND_NAMED TypeRefKind = 2
)

// Enum value maps for TypeRefKind.
var (
	TypeRefKind_name = map[int32]string{
		0: "TYPE_REF_KIND_UNSPECIFIED",
		1: "TYPE_REF_KIND_PRIMITIVE",
		2: "TYPE_REF_KIND_NAMED",
	}
	TypeRefKind_value = map[string]int32{
		"TYPE_REF_KIND_UNSPECIFIED": 0,
		"TYPE_REF_KIND_PRIMITIVE":   1,
		"TYPE_REF_KIND_NAMED":       2,
	}
)

func (x TypeRefKind) Enum() *TypeRefKind {
	p := new(TypeRefKind)
	*p = x
	return p
}

func (x TypeRefKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeRefKind) Descriptor() protoreflect.EnumDescriptor {
	return file_type_ref_kind_proto_enumTypes[0].Descriptor()
}

func (TypeRefKind) Type() protoreflect.EnumType {
	return &file_type_ref_kind_proto_enumTypes[0]
}

func (x TypeRefKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeRefKind.Descriptor instead.
func (TypeRefKind) EnumDescriptor() ([]byte, []int) {
	return file_type_ref_kind_proto_rawDescGZIP(), []int{0}
}

var File_type_ref_kind_proto protoreflect.FileDescriptor

const file_type_ref_kind_proto_rawDesc = "" +
	"\n" +
	"\x13type_ref_kind.proto*b\n" +
	"\vTypeRefKind\x12\x1d\n" +
	"\x19TYPE_REF_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TYPE_REF_KIND_PRIMITIVE\x10\x01\x12\x17\n" +
	"\x13TYPE_REF_KIND_NAMED\x10\x02B)Z'github.com/z5labs/avroc/avrocpb;avrocpbb\beditionsp\xe8\a"

var (
	file_type_ref_kind_proto_rawDescOnce sync.Once
	file_type_ref_kind_proto_rawDescData []byte
)

func file_type_ref_kind_proto_rawDescGZIP() []byte {
	file_type_ref_kind_proto_rawDescOnce.Do(func() {
		file_type_ref_kind_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_type_ref_kind_proto_rawDesc), len(file_type_ref_kind_proto_rawDesc)))
	})
	return file_type_ref_kind_proto_rawDescData
}

var file_type_ref_kind_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_type_ref_kind_proto_goTypes = []any{
	(TypeRefKind)(0), // 0: TypeRefKind
}
var file_type_ref_kind_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_type_ref_kind_proto_init() }
func file_type_ref_kind_proto_init() {
	if File_type_ref_kind_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_type_ref_kind_proto_rawDesc), len(file_type_ref_kind_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_type_ref_kind_proto_goTypes,
		DependencyIndexes: file_type_ref_kind_proto_depIdxs,
		EnumInfos:         file_type_ref_kind_proto_enumTypes,
	}.Build()
	File_type_ref_kind_proto = out.File
	file_type_ref_kind_proto_goTypes = nil
	file_type_ref_kind_proto_depIdxs = nil
}
