name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yaml'
  pull_request:
    branches:
      - "main"
  merge_group:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - name: Checkout
          uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

        - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
          with:
            go-version-file: go.mod

        - name: Lint Go Code
          if: matrix.os == 'ubuntu-latest'
          uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
          with:
            version: latest
            skip-cache: false

        - name: Build
          run: go build ./...

        - name: Test
          run: go test -race -cover ./...

        - name: Build example binaries
          shell: bash
          run: |
            ext=""
            if [ "${{ matrix.os }}" = "windows-latest" ]; then ext=".exe"; fi
            go build -o "./bin/avroc${ext}" ./cmd/avroc
            go build -o "./bin/avroc-gen-go${ext}" ./cmd/avroc-gen-go
            go build -o "./bin/avroc-gen-json${ext}" ./cmd/avroc-gen-json
            go build -o "./bin/avroc-gen-pcf${ext}" ./cmd/avroc-gen-pcf
            ls -la ./bin

        - name: Add bin to PATH
          shell: bash
          run: echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

        - name: Run example
          shell: bash
          working-directory: example
          run: avroc generate

        - name: Verify example output is up to date
          shell: bash
          run: git diff --exit-code -- example
